version: "3.9"

services:
  db-server:
    image: db-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
    depends_on:
      - db 

  ws-server:
    image: ws-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development

  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - type: bind
        source: "./db/my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
      - ./db/log:/var/log/mysql
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:                       
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bingodon}
      MYSQL_USER: ${MYSQL_USER:-bingodon}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      TZ: "Asia/Tokyo"