services:
  db-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: "db-server"
    ports:
      - "5001:5001"
    volumes:
      - /Users/alufu/work/bingo-backend:/app
    environment:
      - GO_ENV=development

  ws-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: "ws-server"
    ports:
      - "5002:5002"
    volumes:
      - /Users/alufu/work/bingo-backend:/app
    environment:
      - GO_ENV=development